### PR TITLE
Update active-0.2

### PR DESCRIPTION
**Pull request by bgamari**
It would be appreciated you could push a revision with these changes.

### CODE REVIEW

**Comment by bgamari** [comment]
Note that it's expected that this merge doesn't apply; I rather just wanted to point out the existence of the branch.

**Comment by byorgey** [comment]
This has been revised on Hackage since October 8.  Is there something else I need to do?

**Comment by bgamari** [comment]
Brent Yorgey <notifications@github.com> writes:

> This has been revised on Hackage since October 8.  Is there something else I need to do?
>
Ahh, I suspect that revision just didn't make it into my nix snapshot. Cheers!

**Comment by byorgey** [comment]
No worries!

**Pull request closed without merging**
